### ISSUE TITLE
关于改进并提交到官方仓库

### ISSUE THREAD

**Issue by oa414** [oa414/puma#1]
我打开了下 issue，把 wiki 上内容移动过来了。  @1c7  

> 为啥不提交到官方 Github 库里面去？
> Cheng Zheng edited this page 3 hours ago · 3 revisions
> 
> 这翻译的很好啊，为啥不去官方 issue 问问能不能加个中文文档到官方库里去？
> (没 Issue 所以只能开个 Wiki)

因为这是几年前自己初学 Puma 配置相关的时候一篇练手的翻译文章，虽然应该没什么大错误，但是行文和排版还是有待提高，就没有打算提交合并了。

而且正如 Ruby－China 里[你的帖子](https://ruby-china.org/topics/30129)下面的跟帖： Puma 的配置也确实不难。(我看到你发的帖子了 :-) )况且 Google 搜 “Puma 服务器” 本文已经排第一了，也能起到帮助到国内的 Puma 初学者了的作用了 😃

**Comment by 1c7** [comment]
嗯，明白了，谢谢。
